name: Update Info.plist Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  increment_version:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug directory structure
      - name: Debug Directory Structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files and directories:"
          ls -R

      # Step 3: Find and update Info.plist
      - name: Increment version and build
        run: |
          INFO_PLIST=$(find ./Example/FalconPodGuide -name "Info.plist" | head -n 1)
          if [ -z "$INFO_PLIST" ]; then
            echo "Error: Info.plist not found."
            exit 1
          fi
          echo "Found Info.plist at $INFO_PLIST"
          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST" 2>/dev/null || echo "0.0.0")
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFO_PLIST" 2>/dev/null || echo "0")
          echo "Current Version: $CURRENT_VERSION, Current Build: $CURRENT_BUILD"
