name: Verify PlistBuddy Availability
  run: ls /usr/libexec/PlistBuddy

name: Check Info.plist Path
  run: |
    echo "INFO_PLIST_PATH: $INFO_PLIST_PATH"
    ls -l $INFO_PLIST_PATH
name: Update Info.plist Version
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  increment_version:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Increment version and build
        run: |
          chmod +x scripts/update_plist.sh
          ./scripts/update_plist.sh
        env:
          INFO_PLIST_PATH: path/to/Info.plist
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add path/to/Info.plist
          git commit -m "Auto-incremented version and build"
          git push
