name: Auto Increment Version and Create PR on Tag Creation
'on':
  push:
    tags:
      - v*
jobs:
  auto_increment_version:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Increment version
        run: |
          chmod +x scripts/version_update_plist.sh
          ./scripts/version_update_plist.sh
        env:
          INFO_PLIST_PATH: ./Example/FalconPodGuide/Info.plist
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          BRANCH_NAME="version-bump/$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Auto-incremented version after tag creation"
          git push origin "$BRANCH_NAME"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: '${{ github.ref_name }}'
          base: main
          title: Version Bump Post Tag Creation
          body: >-
            This PR increments the version and updates Info.plist after tag
            creation.
