name: Assign Team Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  add-team-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Team Reviewers via API
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_AUTO_PR_ASSIGNMENT }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers \
            -d '{"reviewers": ["dil-ABalasubramanian"]}'
